version: "3.7"
services:
  mongodb:
    image: mongo
    ports:
      - "29142:27017"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=app"
      - "MONGO_INITDB_ROOT_PASSWORD=qwe123"
  mongo-express:
    image: mongo-express
    depends_on: 
      - mongodb
    ports:
      - "29143:8081"
    environment:
      - "ME_CONFIG_MONGODB_ADMINUSERNAME=app"
      - "ME_CONFIG_MONGODB_ADMINPASSWORD=qwe123"
      - "ME_CONFIG_MONGODB_SERVER=mongodb"
